server:
  port: 8080
spring:
  application:
    name: "customers_experience"
  profiles:
    active: "default"
  datasource:
    url: jdbc:mysql://localhost:3306/customersdb
    username: root
    password: root
    initialization-mode: always
    platform: mysql
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  cloud:
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"